name: Update WinGet Package

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["Release"]
    types: [completed]
  workflow_dispatch:

jobs:
  winget:
    name: Update winget-pkgs manifest
    if: github.server_url == 'https://github.com' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Update Package
        uses: michidk/winget-updater@v1
        with:
          komac-token: ${{ secrets.KOMAC_TOKEN }}
          identifier: madLinux.dstimer
          repo: madLinux7/dstimer
          url: "https://github.com/madLinux7/dstimer/releases/download/v{VERSION}/dstimer.exe"
